import { Logo } from "./components/Logo/Logo";
import { MainContent } from "./components/MainContent/MainContent";
import { MainMenu } from "./components/MainMenu/MainMenu";
import { TopBar } from "./components/TopBar/TopBar";
import "./styles/globals.css";
import "./styles/theme.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Fashon contemporary shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body>
        <MainContent>
          <TopBar>
            <MainMenu />
            <Logo />
          </TopBar>
          {children}
        </MainContent>
      </body>
    </html>
  );
}
