"use client";

import { CurrencySelector } from "./components/CurrencySelector/CurrencySelector";
import { IconMenu } from "./components/IconMenu/IconMenu";
import { Logo } from "./components/Logo/Logo";
import { MainContent } from "./components/MainContent/MainContent";
import { MainMenu } from "./components/MainMenu/MainMenu";
import { TopBar } from "./components/TopBar/TopBar";
import { CartContext } from "./contexts/CartContext";
import { CurrencyContext } from "./contexts/CurrencyContext";
import { useCart } from "./hooks/useCart";
import { useCurrency } from "./hooks/useCurrency";
import "./styles/globals.css";
import "./styles/theme.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// FIXME: not working in use client mode
// export const metadata = {
//   title: "Fashon contemporary shop",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [currency, setCurrency] = useCurrency();
  const [shoppingCart, setShoppingCart] = useCart();

  return (
    <html lang="pl">
      <body>
        <CurrencyContext value={[currency, setCurrency]}>
          <CartContext value={[shoppingCart, setShoppingCart]}>
            <MainContent>
              <TopBar>
                <MainMenu />
                <Logo />
                <div>
                  <CurrencySelector />
                  <IconMenu />
                </div>
              </TopBar>
              {children}
            </MainContent>
          </CartContext>
        </CurrencyContext>
      </body>
    </html>
  );
}
